### ISSUE TITLE
Fix empty list segfault

### ISSUE THREAD

**Issue by myselfhimself** [myselfhimself/gmic-py#30]
```
>>> img_list = []
>>> gmic.run("sp lena", images=img_list)
[New Thread 0x7fffb2375700 (LWP 16851)]
[New Thread 0x7fffb1b74700 (LWP 16852)]
[New Thread 0x7fffb1373700 (LWP 16853)]
[New Thread 0x7fffb0b72700 (LWP 16854)]
[New Thread 0x7fffb0371700 (LWP 16855)]
[New Thread 0x7fffafb70700 (LWP 16856)]
[New Thread 0x7fffaf36f700 (LWP 16857)]
[New Thread 0x7fffaeb6e700 (LWP 16858)]
[New Thread 0x7fffae36d700 (LWP 16859)]
[New Thread 0x7fffadb6c700 (LWP 16860)]
[New Thread 0x7fffad36b700 (LWP 16861)]
SystemError: ../Objects/listobject.c:307: bad argument to internal function

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
SystemError: <built-in function run> returned a result with an error set
>>> gmic.run("sp lena [0]", images=img_list)
SystemError: ../Objects/listobject.c:307: bad argument to internal function

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
SystemError: <built-in function run> returned a result with an error set
>>> gmic.run(command="sp lena [0]", images=img_list)
SystemError: ../Objects/listobject.c:307: bad argument to internal function

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
SystemError: <built-in function run> returned a result with an error set
>>> gmic.Gmic().run(command="sp lena [0]", images=img_list)
SystemError: ../Objects/listobject.c:307: bad argument to internal function

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
SystemError: <built-in method run of gmic.Gmic object at 0x7ffff7f52258> returned a result with an error set
>>> gmic.run(command="sp lena [0]", images=img_list)

```

**Comment by myselfhimself** [comment]
Fixed : )
